Feature/brands
Naumilya/SHOP.CO pull request #4
Opened 2023-09-18 05:34 UTC by Naumilya

2023-09-18 20:32 UTC, ARH2004 requested changes

2023-09-18 20:32 UTC, ARH2004 commented on src/components/base/brands/TheBrandsSection.vue
> +        <li class="brands__list-item" v-for="brandItem in BrandsList" :key="brandItem.nameBrand">
создай лучше id для каждого объекта и используй в :key

2023-09-18 20:32 UTC, ARH2004 commented on src/components/base/brands/TheBrandsSection.vue
> +const BrandsList = ref<Brands[]>([
нет смысла в ref

2023-09-18 20:32 UTC, ARH2004 commented on src/components/base/logo/BaseLogo.vue
>    margin-top: -7px;
лучше обойтись без отрицательных значений

2023-09-20 10:23 UTC, Naumilya commented on src/components/base/brands/TheBrandsSection.vue
> +        <li class="brands__list-item" v-for="brandItem in BrandsList" :key="brandItem.nameBrand">
Сделал

2023-09-20 10:25 UTC, Naumilya commented on src/components/base/brands/TheBrandsSection.vue
> +const BrandsList = ref<Brands[]>([
сделал

2023-09-20 10:26 UTC, Naumilya commented on src/components/base/logo/BaseLogo.vue
>    margin-top: -7px;
сделал

2023-09-22 17:10 UTC, merged