add Card template and add New Arrivals section
Naumilya/SHOP.CO pull request #5
Opened 2023-09-19 19:25 UTC by Naumilya

2023-09-19 20:32 UTC, ARH2004 requested changes

2023-09-19 20:32 UTC, ARH2004 commented on src/api/getProducts.ts
> +    return error
`console.error(error.message)`

2023-09-19 20:32 UTC, ARH2004 commented on src/components/base/CardProduct/CardProduct.vue
> +          v-if="!Number.isInteger(props.product.ratingProduct) && props.product.ratingProduct !== 5"
По хорошему это нужно вынести в отдельную функцию

2023-09-19 20:32 UTC, ARH2004 commented on src/components/base/CardProduct/CardProduct.vue
> +        <iconStar v-for="star in Math.floor(props.product.ratingProduct)" :key="star" />
По хорошему это нужно вынести в отдельную функцию

2023-09-19 20:32 UTC, ARH2004 commented on src/components/base/CardProduct/CardProduct.vue
> +    return (
нет смысла брать в скобки

2023-09-19 20:32 UTC, ARH2004 commented on src/components/base/CardProduct/CardProduct.vue
> +      font-weight: 700;
можно использовать миксин

2023-09-19 20:32 UTC, ARH2004 commented on src/components/base/CardProduct/CardProduct.vue
> +      padding: 6px 13px;
можно использовать миксин

2023-09-19 20:32 UTC, ARH2004 commented on src/components/common/ProductCardsTemplate/ProductCards.vue
> +  pricesDiscount?: number
сделай
export interface Product
и просто импорти везде, где тебе нужно
не нужно будет каждый раз определять новый интерфейс и переделывать в всех местах, в случае изменения

2023-09-19 20:32 UTC, ARH2004 commented on src/scss/fonts.scss
> +  font-weight: 700;
можно создать динамический параметр для font-weight

2023-09-20 09:39 UTC, Naumilya commented on src/components/base/CardProduct/CardProduct.vue
> +    return (
Это prettier автоматом ставит

2023-09-20 10:04 UTC, Naumilya commented on src/components/common/ProductCardsTemplate/ProductCards.vue
> +  pricesDiscount?: number
сделал

2023-09-20 10:05 UTC, Naumilya commented on src/scss/fonts.scss
> +  font-weight: 700;
сделал

2023-09-20 10:10 UTC, Naumilya commented on src/components/base/CardProduct/CardProduct.vue
> +      padding: 6px 13px;
сделал

2023-09-20 10:14 UTC, Naumilya commented on src/components/base/CardProduct/CardProduct.vue
> +      font-weight: 700;
сделал

2023-09-20 10:16 UTC, Naumilya commented on src/components/base/CardProduct/CardProduct.vue
> +    return (
Исправил, использовал тернарник

2023-09-20 10:16 UTC, Naumilya commented on src/components/base/CardProduct/CardProduct.vue
> +        <iconStar v-for="star in Math.floor(props.product.ratingProduct)" :key="star" />
Сделал

2023-09-20 10:17 UTC, Naumilya commented on src/api/getProducts.ts
> +    return error
Сделал, НО юзаю Any

2023-09-20 21:56 UTC, merged